# Generated by Django 5.0.1 on 2024-04-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='user2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
