# Generated by Django 5.0.1 on 2024-01-18 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('isAttemptedFirst', models.BooleanField(default=False)),
                ('isAttemptedSecond', models.BooleanField(default=False)),
                ('current_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=255)),
                ('user1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='teamtable',
            name='current_question_id',
        ),
        migrations.DeleteModel(
            name='UserTable',
        ),
        migrations.AddField(
            model_name='progress',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='quiz_app.team'),
        ),
        migrations.DeleteModel(
            name='TeamTable',
        ),
    ]
