# Generated by Django 5.0.1 on 2024-04-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='correct_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='incorrect_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
