# Generated by Django 5.0.1 on 2024-01-19 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_progress_team_remove_teamtable_current_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='current_question',
        ),
        migrations.AddField(
            model_name='progress',
            name='current_questions',
            field=models.TextField(default=datetime.datetime(2024, 1, 19, 16, 43, 56, 135217, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('JR', 'Junior'), ('SR', 'Senior')], default=datetime.datetime(2024, 1, 19, 16, 44, 1, 99481, tzinfo=datetime.timezone.utc), max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('E', 'Easy'), ('H', 'Hard')], default=datetime.datetime(2024, 1, 19, 16, 44, 6, 324391, tzinfo=datetime.timezone.utc), max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('JR', 'Junior'), ('SR', 'Senior')], default='some_default_value', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
    ]
