# Generated by Django 5.0.1 on 2024-01-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_alter_progress_end_time_alter_progress_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='current_questions',
        ),
        migrations.AddField(
            model_name='progress',
            name='current_questions',
            field=models.ManyToManyField(to='quiz_app.question'),
        ),
    ]
