# Generated by Django 5.0.1 on 2024-01-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_remove_progress_current_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='current_questions',
        ),
        migrations.AddField(
            model_name='progress',
            name='current_questions',
            field=models.TextField(default=''),
        ),
    ]
