# Generated by Django 5.0.1 on 2024-01-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_alter_progress_current_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='login_status',
            field=models.BooleanField(default=False),
        ),
    ]
