# Generated by Django 5.0.1 on 2024-01-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_team_login_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='current_questions',
            new_name='question_list',
        ),
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.AddField(
            model_name='progress',
            name='current_question',
            field=models.IntegerField(default=1),
        ),
    ]
