# Generated by Django 5.0.1 on 2024-01-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_rename_current_questions_progress_question_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='isAttemptedSecond',
        ),
    ]
