# Generated by Django 5.0.1 on 2024-01-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0011_alter_team_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='question_list',
            field=models.CharField(max_length=256),
        ),
    ]
