# Generated by Django 5.0.1 on 2024-02-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0012_alter_progress_question_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='prev_answer',
            field=models.IntegerField(default=0),
        ),
    ]
