# Generated by Django 4.2 on 2024-02-16 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0014_alter_progress_end_time_alter_progress_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='lifeline1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='lifeline2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='lifeline3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='lifeline_flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='progress',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 14, 11, 47, 260834, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='progress',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 14, 11, 47, 260834, tzinfo=datetime.timezone.utc)),
        ),
    ]
