# Generated by Django 5.0.1 on 2024-03-27 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0018_question_responses_alter_progress_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 17, 21, 51, 984812, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='progress',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 17, 21, 51, 984812, tzinfo=datetime.timezone.utc)),
        ),
    ]
