# Generated by Django 5.0.1 on 2024-03-27 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0019_alter_progress_end_time_alter_progress_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 17, 23, 1, 932499, tzinfo=datetime.timezone.utc)),
        ),
    ]
