# Generated by Django 5.0.1 on 2024-03-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0020_alter_progress_end_time_alter_progress_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
