# Generated by Django 5.0.1 on 2024-03-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0021_alter_progress_end_time_alter_progress_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='lifeline_flag',
            field=models.SmallIntegerField(default=1),
        ),
    ]
