# Generated by Django 5.0.1 on 2024-03-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0022_alter_progress_lifeline_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
